## Pytorch Basics

### Import Libraries

In [1]:
import torch

### Initialise tensors

In [2]:
x = torch.ones(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [3]:
x = torch.zeros(3, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [5]:
x = torch.rand(3, 2)
print(x)

tensor([[0.0216, 0.3177],
        [0.1817, 0.3137],
        [0.8899, 0.9974]])


In [6]:
x = torch.empty(3, 2)
print(x)

tensor([[ 2.5997e-23,  4.5573e-41],
        [-5.6964e-15,  3.0808e-41],
        [ 4.4842e-44,  0.0000e+00]])


In [7]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
x = torch.linspace(0, 1, steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [9]:
x = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


### Slicing tensors

In [10]:
print(x.size())

torch.Size([3, 2])


In [11]:
print(x[:, 1])

tensor([2, 4, 6])


In [12]:
print(x[0, :])

tensor([1, 2])


In [13]:
y = x[1, 1]
print(y)

tensor(4)


In [14]:
# Gives the element inside tensor
print(y.item())

4


### Reshaping tensors

In [15]:
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [16]:
# Re-arranges the elements into matrix given by view
y = x.view(2, 3)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [17]:
# Another example
y = x.view(1, 6)
print(y)

tensor([[1, 2, 3, 4, 5, 6]])


In [18]:
# Another example
y = x.view(6, -1)
# -1 stands for adjust the matrix appropriately
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


### Simple Tensor Operations

In [19]:
x = torch.ones([3, 2])
y = torch.ones([3, 2])
z = x + y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [20]:
z = x * y
print(z)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [21]:
z = y.add(x)
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [22]:
print(y)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [23]:
z = x - y
print(z)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [26]:
z = y.sub(x)
print(z)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [27]:
# Inplace addition
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
