## Pytorch <> Numpy

### Import Libraries

In [1]:
import torch
import numpy as np

### Initialise tensors

In [2]:
x = torch.ones(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


### Interface to Numpy

In [3]:
x_np = x.numpy()
print(x_np)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
print(type(x), type(x_np))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [6]:
a = np.random.randn(5)
print(a)

[-0.7207332   0.29851105 -0.95457196  0.29011992 -1.44566373]


In [7]:
a_pt = torch.from_numpy(a)
print(a_pt)

tensor([-0.7207,  0.2985, -0.9546,  0.2901, -1.4457], dtype=torch.float64)


In [8]:
print(type(a), type(a_pt))

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [9]:
# Any changes made to a will reflect in torch version of a
np.add(a, 1, out=a)
print(a)
print(a_pt)

[ 0.2792668   1.29851105  0.04542804  1.29011992 -0.44566373]
tensor([ 0.2793,  1.2985,  0.0454,  1.2901, -0.4457], dtype=torch.float64)


### Speed Benchmark

In [10]:
%%time
for i in range(100):
    a = np.random.randn(100, 100)
    b = np.random.randn(100, 100)
    c = a + b

CPU times: user 61.8 ms, sys: 9 µs, total: 61.8 ms
Wall time: 60.5 ms


In [12]:
%%time
for i in range(100):
    a = torch.randn([100, 100])
    b = torch.randn([100, 100])
    c = a + b

CPU times: user 22.5 ms, sys: 245 µs, total: 22.8 ms
Wall time: 22.4 ms


In [13]:
%%time
for i in range(100):
    a = np.random.randn(100, 100)
    b = np.random.randn(100, 100)
    c = np.matmul(a, b)

CPU times: user 311 ms, sys: 0 ns, total: 311 ms
Wall time: 287 ms


In [14]:
%%time
for i in range(100):
    a = torch.randn([100, 100])
    b = torch.randn([100, 100])
    c = torch.matmul(a, b)

CPU times: user 153 ms, sys: 0 ns, total: 153 ms
Wall time: 98.3 ms
